### ISSUE TITLE
preprocess-obtain-lungmasks

### ISSUE THREAD

**Issue by jiejiangd** [sydney0zq/covid-19-detection#2]
想问一下代码中
preprocess-obtain-lungmasks我用了自己的数据未能得到mask的结果，尝试了多个数据都是一样，想请问一下您我还有什么未注意到的地方吗
![图片](https://user-images.githubusercontent.com/46582999/82427142-470fc880-9abb-11ea-9b25-80a148251344.png)

**Comment by theodoruszq** [comment]
您好，您可以打印出来一些中间结果么，如果方便的话，可以将CT dicom文件单独发给我么，我帮您看一下。我的邮箱是: theodoruszq@gmail.com

**Comment by jiejiangd** [comment]
&nbsp;您好，我目前遇到一个问题就是一个三分类里面有一个类始终能分对，但是其他两个类会有博弈的过程，我考虑的是会不会这个类和其他两个类有本质上的差异（结果就是确实这个类的平均像素值低于其他两个类），想请问您在做临床数据时针对不同机型不同的图片需要做什么预处理吗，我目前只转换了HU值和根据窗位窗宽进行归一化。
非常感谢您的回复！
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by theodoruszq** [comment]
@jiejiangd 我这边在做实验的时候，默认都是一个机型来对待的（实际不是），实际用肉眼看差距感觉也不是很大。有一些机型可能确实会导致空气部分HU值过高或过低的问题，不过在我的处理的大概几百个CT样本中是非常少见的。

此外，如果将肺部单独crop出来，我认为crop之后的图像在某一类的平均值上应该不会和其他类有显著的差异。我不太清楚您说的竞争问题具体指什么，或许您可以从这个repo中获取一些灵感，他这边就是做的3分类：https://github.com/bkong999/COVNet。

**Comment by jiejiangd** [comment]
&nbsp;我刚才看了他的感觉只做了阈值截取和标准化
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by theodoruszq** [comment]
@jiejiangd 关于您在预处理方面的问题，我这边可能无法给您更多的建议，可以参考一些论文或者其他相关文献。
