### ISSUE TITLE
Image has wrong mode in dataste_ops.py using deCoVnet

### ISSUE THREAD

**Issue by bartmch** [sydney0zq/covid-19-detection#3]
Hi, while train.py from deCoVnet I'm getting an error from dataset_ops.py at line 108
`    # Color Transforms
    def colorop(img, bright, contrast):
        _img = TF.adjust_brightness(img, bright)
        _img = TF.adjust_contrast(_img, contrast)
        return _img`
the error is saying

> ValueError: image has wrong mode

Image is a PIL image and bright is a float
![image](https://user-images.githubusercontent.com/10415569/84973058-33df2f80-b131-11ea-9560-2de122befd6b.png)

**Comment by bartmch** [comment]
`TF.adjust_brightness(img.convert('L'), bright)` seems to work. Can you confirm this doesn't break the image?

**Comment by theodoruszq** [comment]
@bartmch Sorry for the late reply. Please check the shape of img, it should be in HxWxC and the datatype of it should be 'uint8', otherwise the error will prompt. I think maybe you input a 16bit image into this function.
