### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by AlexTS1980** [sydney0zq/covid-19-detection#4]
Where can I find the images? NpyData directories contain only empty files

**Comment by Wangnaijia** [comment]
You can got the datasets on this website.[https://www.graviti.cn/open-datasets/dataset-detail/COVID-CT](url)

**Comment by Wangnaijia** [comment]
You can get the datasets on this website [https://www.graviti.cn/open-datasets/dataset-detail/COVID-CT](url)

**Comment by theodoruszq** [comment]
@AlexTS1980  Sorry the dataset we cannot make it public available due to privacy issues. You can use the dataset provide by @Wangnaijia  for research. If you have any problem, feel free to leave your problem here.
